-- 현재 관리자 데이터 → MySQL 시드 (자동생성)
SET NAMES utf8mb4;

-- ⚠️관리자 계정은 이 파일에 넣지 않습니다.
-- (배포 시 웹루트로 복사되면 SQL이 그대로 다운로드돼 계정 해시가 노출됨 — 2026-07-28 실제 발생)
-- 설치 시 아래를 직접 실행해 원하는 비밀번호로 생성하세요.
--   SET @pw := '여기에_새_비밀번호';
--   INSERT INTO `admins`(username,password_hash,created_at)
--     VALUES('admin', SHA2(@pw, 256), CURDATE());

-- 포트폴리오 450개
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_db25b9d483b526.jpg','식품안전정보원','카탈로그','책자',0);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1577faf6f0e11e.jpg','네이처셋 키즈','로고 · 브랜딩','로고',1);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9cbb4f7863e1ca.jpg','NHN토스트캠','리플렛','리플릿',2);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9db27148eb2af1.jpg','대구한의대학교 홍삼경옥골드','패키지','촬영',3);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4a1a0190e84389.jpg','명품세계여행','포스터','기타',4);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_081a3a559a4d9a.jpg','주식회사 동남','브로슈어','책자',5);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b08785c6c4bf16.jpg','비오에이','로고 · 브랜딩','로고',6);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a207ab548aa58f.jpg','아이에프시스','리플렛','리플릿',7);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3ebe56da6e5d79.jpg','은행길 전통장','패키지','촬영',8);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_dc7dec02cdb051.jpg','케이워터테크','포스터','기타',9);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_d85ef73b856bd0.jpg','크림슨에듀케이션','카탈로그','책자',10);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e950e7af418f63.png','승진팩토리','로고 · 브랜딩','로고',11);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c40abf539a7d26.jpg','탐스디자인','리플렛','리플릿',12);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a7f0ccb92b5516.jpg','오케이올인원클렌저','패키지','촬영',13);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_7708fb9cb512c3.jpg','서초여성일자리 주식회사','포스터','기타',14);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8dbe446177a4cc.jpg','한국은행','브로슈어','책자',15);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_95cf640f796df8.jpg','내당1동제일골목','로고 · 브랜딩','로고',16);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8884e341cb62af.jpg','짐컴퍼니','리플렛','리플릿',17);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_14b3d6014d77b3.jpg','HEAT','패키지','촬영',18);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_85607812d3cc92.jpg','전국렌터카공제조합','포스터','기타',19);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_714daac6f246ee.jpg','HLB제약','카탈로그','책자',20);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8315cad41d7639.jpg','리비','로고 · 브랜딩','로고',21);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_bc4ae5272e67b0.jpg','스포츠산업일자리센터','리플렛','리플릿',22);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_bd95e5575f81c7.jpg','꼬소명가','패키지','촬영',23);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8f35629fc1ea9d.jpg','부산테크노파크','포스터','기타',24);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_63f5f796e2e49f.jpg','포스랩','브로슈어','책자',25);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_06af0e34cf6fab.jpg','비엔에스비즈','로고 · 브랜딩','로고',26);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_54631fbc105a3a.jpg','돗토리현','쿠폰북','리플릿',27);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5782f824e00e05.jpg','트루바이오텍','촬영 · 콘텐츠','촬영',28);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b07922ac9eef1f.jpg','레디큐','포스터','기타',29);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ebd95a329f277a.jpg','되고시스템','브로슈어','책자',30);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_6bbafeef09ad92.jpg','테니스스팟','로고 · 브랜딩','로고',31);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2944d6e75b326d.jpg','에이에스이천안(주)','리플렛','리플릿',32);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e047cb05d01ed8.jpg','이든제이','촬영 · 콘텐츠','촬영',33);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c6170f7beae0e6.jpg','써모피셔 스마트 컨택센터','포스터','기타',34);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2bce233893d236.jpg','솔탑','브로슈어','책자',35);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_d53aab4ea30346.jpg','주식회사 유엔에이','로고 · 브랜딩','로고',36);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_fb8f4528693bb3.jpg','한국고분자소재연구조합','리플렛','리플릿',37);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ddcc9de681ce18.jpg','연세유업','촬영 · 콘텐츠','촬영',38);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_7585400e54b661.jpg','한국중앙자원봉사 콘텐츠 공모전','포스터','기타',39);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_0ac2e3fb32e767.jpg','윌로펌프','브로슈어','책자',40);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_45af1a5e4eceac.jpg','트레비티','로고 · 브랜딩','로고',41);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_20de6a356e7880.jpg','포스코기술연계센터','리플렛','리플릿',42);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_eabeb27d4a968a.jpg','진바이오텍','촬영 · 콘텐츠','촬영',43);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_49e88c239755ca.jpg','청소년 디지털 디톡스 활동단','포스터','기타',44);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5f8f57612bf7c6.jpg','위미코','브로슈어','책자',45);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e4b6488aae6152.jpg','아파트커넥션','로고 · 브랜딩','로고',46);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9ce27e93122ff3.jpg','유한기술(주)','리플렛','리플릿',47);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_88818940f82f5a.jpg','미라엔젤','촬영 · 콘텐츠','촬영',48);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_fb0785ec8a697c.jpg','이화여자대학교','포스터','기타',49);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ee35c9e8bb677f.jpg','펩트론','브로슈어','책자',50);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_693f024548ebde.jpg','디아이정밀','로고 · 브랜딩','로고',51);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1eaef4eeb86dde.jpg','골든모닝에프엔비','리플렛','리플릿',52);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ca35c0056582ac.jpg','이뮤노바이오텍','촬영 · 콘텐츠','촬영',53);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_0cb4cfea3df756.jpg','연세대학교 자살예방상담전화','포스터','기타',54);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_33e89fc8032013.jpg','대구228기념학생도서관','독서기록장','책자',55);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2c5e9796eabe6f.jpg','아루넬','로고 · 브랜딩','로고',56);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_0e3f391cc3812d.jpg','오산시환경사업소','리플렛','리플릿',57);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8f554cb6320b2e.jpg','더건강협동조합','촬영 · 콘텐츠','촬영',58);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9c0d128bdc5891.jpg','서세종대 캠퍼스타운','포스터','기타',59);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1c07931e01af36.jpg','태성','카탈로그','책자',60);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e5c00fa3e4e61b.jpg','에이엔에이치코리아','로고 · 브랜딩','로고',61);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1497725ccffb63.jpg','스카이오프쇼어','리플렛','리플릿',62);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3c3594d8a32e52.jpg','랩팩토리','촬영 · 콘텐츠','촬영',63);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3cdf36f562ae7c.jpg','경주경찰서 다문화가족을 위한 범죄예방수칙','포스터','기타',64);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_6b2feb6f2a619d.jpg','동양케미컬','브로슈어','책자',65);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_36861992be7aad.jpg','청춘애찬','로고 · 브랜딩','로고',66);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_96fb1960c36d0d.jpg','한국가스안전공사','리플렛','리플릿',67);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_90eb5a43e7fe72.jpg','비스비바','촬영 · 콘텐츠','촬영',68);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_701a44a84aec30.jpg','서울시립대 발전기금 캠페인','포스터','기타',69);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c854050dc7a486.jpg','KT&G','브로슈어','책자',70);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ee60a00765e9e6.jpg','대가야철갑상어','로고 · 브랜딩','로고',71);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_74c6834593379d.jpg','진에딧코리아 유한회사','리플렛','리플릿',72);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_73429b855dd0ff.jpg','퓨전에','촬영 · 콘텐츠','촬영',73);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_d669fd48568d67.jpg','서대문구 책이음','포스터','기타',74);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1b456cefe45895.jpg','신용회복위원회','브로슈어','책자',75);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a093c556fb54ca.jpg','예스레이블텍','로고 · 브랜딩','로고',76);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_09d7c4c68be3fc.jpg','클라우드시스템','리플렛','리플릿',77);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_0a2e6e8222f295.jpg','한빛침장','촬영 · 콘텐츠','촬영',78);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_bd58c450b3f999.jpg','서강 스타트업 서바이벌','포스터','기타',79);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5333de4279db1f.jpg','덱스레보','브로슈어','책자',80);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1a47ab1e1535c4.jpg','번창식품','로고 · 브랜딩','로고',81);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_72266183b76ec3.jpg','유플러스시스템','리플렛','리플릿',82);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8022bc43997331.jpg','쇼어','촬영 · 콘텐츠','촬영',83);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3d1f77debc594e.jpg','서울여대 &노원구 여성 음주 폐해 예방 교육','포스터','기타',84);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5c64b3d6d2c9be.jpg','GS칼텍스','브로슈어','책자',85);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_57f779cb2963c6.jpg','한국문화융합학회','로고 · 브랜딩','로고',86);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_20566e2a478207.png','위미코','리플렛','리플릿',87);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_6fd7a49e21d087.jpg','레드밴스','촬영 · 콘텐츠','촬영',88);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_dd45ec10fdebaf.jpg','국민은행 ISA 세테크','포스터','기타',89);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_621088ee03be8b.jpg','지오에이치텍','브로슈어','책자',90);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_7af1995e5fab45.jpg','머슬119','로고 · 브랜딩','로고',91);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3a435e7b144d68.jpg','온코크로스','리플렛','리플릿',92);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e655bc4e956d30.jpg','주식회사오월','촬영 · 콘텐츠','촬영',93);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_28e4a7bd977a17.jpg','강남구 보건소','포스터','기타',94);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_42e4412eaca90d.jpg','진바이오텍','카탈로그 · 브로슈어','책자',95);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2e14c79678f064.jpg','네이처셋','로고 · 브랜딩','로고',96);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c0537000dad758.jpg','한국산업지능화협회','리플렛','리플릿',97);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_6a1837fb72a860.jpg','애플카렌다','촬영 · 콘텐츠','촬영',98);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_f2faf5dd319aea.jpg','국민은행 생활 SOC 공익신탁','포스터','기타',99);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_cb50786d334ec9.jpg','지티에스','카탈로그 · 브로슈어','책자',100);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_35928568057517.jpg','원앤유씨엔테크','로고 · 브랜딩','로고',101);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1a27f1db325072.jpg','캐니캐티케어','리플렛','리플릿',102);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8c85598c867ae7.jpg','김민재 편백치드','촬영 · 콘텐츠','촬영',103);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8d1c3a75b0f3ea.jpg','서울예술실용전문학교 주얼리디자인공모전','포스터','기타',104);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_fdbb173ceffcc0.jpg','전국렌터카공제조합','카탈로그 · 브로슈어','책자',105);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8ffdf994788e54.jpg','로지센','로고 · 브랜딩','로고',106);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5ec80d8d223cd1.jpg','솔리드뷰','리플렛','리플릿',107);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_fe11c5db26f403.jpg','마르벤코리아','촬영 · 콘텐츠','촬영',108);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a895c0296c0870.jpg','스마트쎈클래스','포스터','기타',109);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ad01aa926e03ac.jpg','과학기술센타','브로슈어','책자',110);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5b199511f727d9.jpg','늘품','로고 · 브랜딩','로고',111);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9c31e37fdd4008.jpg','이비스 스타일 앰버서더 전주 시티센터','리플렛','리플릿',112);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e21e718c4a386c.jpg','베어그릭스','촬영 · 콘텐츠','촬영',113);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3b20453038a462.jpg','이화여대','포스터','기타',114);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_0e5f278fecec03.jpg','케이티엠테크','카탈로그','책자',115);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5495c22e3e9a8a.jpg','이진종합건설','로고 · 브랜딩','로고',116);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c8e3f399dae582.jpg','베이의원','리플렛','리플릿',117);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9d4c9361169ae0.jpg','퓨전에프엔씨','촬영 · 콘텐츠','촬영',118);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ebbdcbc9d9abdb.jpg','서울시립대','포스터','기타',119);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_83c4fbcccd34d7.jpg','일신오토클레이브','브로슈어','책자',120);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_7e2e3951351eb8.jpg','명가푸드시스템','로고 · 브랜딩','로고',121);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9a44350a8ed6b5.jpg','다이폴라','리플렛','리플릿',122);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_638284f0eeb98a.jpg','프렌즈미','촬영 · 콘텐츠','촬영',123);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_aedd7628b4631f.jpg','스페이스솔루션','브로슈어','책자',124);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_440db84465f920.jpg','리버스전자','로고 · 브랜딩','로고',125);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a3abe0d335eefc.jpg','한국학중앙연구원','리플렛','리플릿',126);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_6874873a601a42.jpg','아이씨컴퍼니','촬영 · 콘텐츠','촬영',127);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ca3a312df1737e.jpg','비어프렌드','브로슈어','책자',128);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_f9e146669967fb.jpg','푸드트립','로고 · 브랜딩','로고',129);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_0f6022590b4e0e.jpg','영자닷컴','리플렛','리플릿',130);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_cbd4c54be45c45.jpg','싸주아리','촬영 · 콘텐츠','촬영',131);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b1088f4b0d8a96.jpg','톨레미시스템','브로슈어','책자',132);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_f0aedae635d781.jpg','태산머터리얼즈','로고 · 브랜딩','로고',133);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5305ec61e7dabe.jpg','배산초등학교','리플렛','리플릿',134);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3a74cf841ad24a.jpg','레츠퀸','촬영 · 콘텐츠','촬영',135);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_be4137c558654c.jpg','뉴로모빌리티','카탈로그','책자',136);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3a4e0d9a07bbe9.jpg','제이에이치에너지건설','로고 · 브랜딩','로고',137);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_752e92bc586dfb.jpg','온실가스국제감축산업협회','리플렛','리플릿',138);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2812d9f73a0008.jpg','레이퀸','촬영 · 콘텐츠','촬영',139);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b2cf02bdd0b107.jpg','페녹스코리아','카탈로그','책자',140);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_adf99ffa677de0.jpg','얼라이브돌스','로고 · 브랜딩','로고',141);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a45c20c8a4cfd3.jpg','일본무역진흥기구','리플렛','리플릿',142);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_d98d9021c48fb5.jpg','네이쳐커넥트','촬영 · 콘텐츠','촬영',143);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_6484b529254fd2.jpg','에코데이인터내셔널','브로슈어','책자',144);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1c825bc74b2d51.jpg','그린마이스','로고 · 브랜딩','로고',145);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_d911afa95f50be.jpg','용인시건강지원센터','리플렛','리플릿',146);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_cc2b9dc514a434.jpg','BONBON','촬영 · 콘텐츠','촬영',147);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b2a6077e0c355b.jpg','상원아이앤디','카탈로그','책자',148);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_750062fc9abde1.jpg','C&E네트웍스','로고 · 브랜딩','로고',149);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_199793c81ca77f.jpg','아이겐드럭','리플렛','리플릿',150);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c053e97c18996d.jpg','BOB','촬영 · 콘텐츠','촬영',151);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_f9c4e4dd10e359.jpg','메디코스바이오텍','브로슈어','책자',152);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_139a0fb6422c13.jpg','상장회사진흥원','로고','로고',153);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4c84795ed7a910.png','BMC','리플렛','리플릿',154);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_d578bb87db5185.jpg','표준협회','촬영 · 콘텐츠','촬영',155);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2c30800bdad728.jpg','에드모텍','브로슈어','책자',156);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_af15278ca196c1.jpg','박종임소담장','로고','로고',157);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_545bbdd3410f52.jpg','메디로버','팜플렛','리플릿',158);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_db660303cf95ed.jpg','주식회사 오키','촬영 · 콘텐츠','촬영',159);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a103049d79043a.jpg','와이바이오로직스','브로슈어','책자',160);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_6dc954d1647ba9.jpg','J&K플러스','로고','로고',161);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_97cc0897491f3c.jpg','레드인터내셔널','팜플렛','리플릿',162);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8930dc41329b2d.png','페로제','촬영 · 콘텐츠','촬영',163);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_bb7361d4f9c105.jpg','신성화학','브로슈어','책자',164);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_86386b0b2dfc88.jpg','한국공공언어연구협회','로고','로고',165);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_27f490a5b9128e.jpg','내곡도서관','팜플렛','리플릿',166);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_69de571647318c.jpg','돌아이뷰티','촬영 · 콘텐츠','촬영',167);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_f74070a2230360.jpg','미래해양','카탈로그','책자',168);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_0a01da1a596c29.jpg','하나로골프','로고','로고',169);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_44e04d1d5d198a.jpg','가산메탈','팜플렛','리플릿',170);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c9e03b6e7fd218.jpg','코지화이트','촬영 · 콘텐츠','촬영',171);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_7ee6989e99cf24.jpg','팔수','브로슈어','책자',172);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1e68eca81e68a4.jpg','야미부산','로고','로고',173);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_297a3a26e8d302.jpg','이공컨스','리플렛','리플릿',174);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a513b289a59651.jpg','티큐라','촬영 · 콘텐츠','촬영',175);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c2a80e4f19c2af.jpg','아이옵스','브로슈어','책자',176);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_cf473ecde1f88f.jpg','센트럴스타','로고','로고',177);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_790325d2f856e9.jpg','한국외대','리플렛','리플릿',178);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2e44a91bcc7b71.jpg','주식회사오키','촬영 · 콘텐츠','촬영',179);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_37eda259111c24.jpg','신한신용정보','브로슈어','책자',180);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5a1f765828c41d.jpg','한국문화융합협회','로고','로고',181);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8c4f7946bbf595.jpg','포스트건설','리플렛','리플릿',182);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4100d9432e506d.jpg','페이스푸드','촬영 · 콘텐츠','촬영',183);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3684d3ef6317b9.jpg','신도열기 제품소개','카탈로그','책자',184);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4ce21ced639f1f.jpg','푸드아레나','로고','로고',185);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1b10bacd07b204.jpg','덕성여대','리플렛','리플릿',186);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a63585d6be3071.jpg','로얄브론즈','촬영 · 콘텐츠','촬영',187);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_77ebad0d373c01.jpg','셀퓨릭스','브로슈어','책자',188);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5c4cfe78faa162.jpg','위아','로고','로고',189);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_0a4bc4122fb199.jpg','후지필름','리플렛','리플릿',190);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_178e5b5f59aebd.jpg','더나인스킨','촬영 · 콘텐츠','촬영',191);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_117684da15adcd.jpg','한우테크','카탈로그','책자',192);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_823ee6c0efc24d.jpg','예스레이블텍','로고','로고',193);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_7e34c4d38fa732.jpg','한국폴리텍대학','리플렛','리플릿',194);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_f8588e40573ced.jpg','단디컴퍼니','촬영 · 콘텐츠','촬영',195);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_69360b729b76b9.jpg','한국교직원공제','카탈로그','책자',196);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_755d11342179da.jpg','성신브이엠피','로고','로고',197);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_eb8e85e704565f.jpg','KB금융그룹','리플렛','리플릿',198);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_130e6ea9b3c4d8.jpg','메디앤리서치','촬영 · 콘텐츠','촬영',199);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_28e8e192850d04.jpg','하나영농조합','카탈로그','책자',200);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_eb97525209da62.jpg','빅바틀 유니버스','로고','로고',201);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3953154781395a.jpg','국민은행','리플렛','리플릿',202);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_877fe1d8909862.jpg','이세계포션상점','촬영 · 콘텐츠','촬영',203);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_fa1bb91b609f98.jpg','프로축구연맹','카탈로그','책자',204);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1ac868041005f6.jpg','부산대학교','로고','로고',205);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1d511a37f8f6ee.jpg','현대요트','리플렛','리플릿',206);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8eac670d6eb126.jpg','지원바이오','촬영 · 콘텐츠','촬영',207);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3f6d1b0774bfee.jpg','인바디','카탈로그','책자',208);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ef67397059aad4.jpg','벤텍사이언스','로고','로고',209);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_10f94bdb875aeb.jpg','영남대학교','리플렛','리플릿',210);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_57953ced75a7cd.jpg','티크라 아크솔','촬영 · 콘텐츠','촬영',211);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_229f8e82a02be0.jpg','올림픽코리아','카탈로그','책자',212);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ff418a62b96f03.jpg','에코 팩토리얼','로고','로고',213);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9cc3ace57f25ae.jpg','카이스트','리플렛','리플릿',214);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5c2615abcd277f.jpg','한국비앤씨','촬영 · 콘텐츠','촬영',215);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_66fb7e3d50ea3e.jpg','스와로브스키','카탈로그','책자',216);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_7dbb6f3f72441f.jpg','힐링다나','로고','로고',217);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9f0d0f8d3c6cd9.jpg','서울대학교','리플렛','리플릿',218);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_56c1fea614977a.jpg','한양네트웤스','촬영 · 콘텐츠','촬영',219);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4c8f98b6f43405.jpg','서초문화재단','카탈로그','책자',220);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e7272945eea8da.jpg','스터디피디','로고','로고',221);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_cfe9b8f650a984.jpg','삼성 바이오','리플렛','리플릿',222);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c2e83a2212b9b1.jpg','카스인바이오','촬영 · 콘텐츠','촬영',223);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1390daf9f3d2e1.jpg','단양군청','카탈로그','책자',224);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_29c264a9d46b47.jpg','공간이음','로고','로고',225);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2fc6d1b0d6a554.jpg','삼성화재','리플렛','리플릿',226);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e2653b48ca53be.jpg','아틀리에비','촬영 · 콘텐츠','촬영',227);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a2032fe9a68857.jpg','관용사','카탈로그','책자',228);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b4743542499e0e.jpg','셔플스튜디오','로고','로고',229);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e3b7bca4719020.jpg','미래에셋','리플렛','리플릿',230);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_16cb72b68c72e8.jpg','에필로즈','촬영 · 콘텐츠','촬영',231);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_51b3549168fab6.jpg','효동선박','카탈로그','책자',232);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e36c36f430429e.jpg','k오가닉','로고','로고',233);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a162549b56aab4.jpg','하이트 진로','리플렛','리플릿',234);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_23940eec63a571.jpg','모스트롱','촬영 · 콘텐츠','촬영',235);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5b17f4a60dc0ff.jpg','화락치킨','카탈로그','책자',236);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_cf6314fc281bc9.jpg','SG 솔루션','로고','로고',237);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a855a6bfba134d.jpg','경찰청','팜플렛','리플릿',238);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5a4fa853bcf83c.jpg','레이델','촬영 · 콘텐츠','촬영',239);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_be64a50727c7fe.jpg','김민재 편백치드','카탈로그','책자',240);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_0371cfbe4963ab.jpg','프롬비랩 CICA','로고 · 브랜딩','로고',241);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b5f7d777dd63da.jpg','케이엑스넥스지','팜플렛','리플릿',242);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a68c0ea0b30ae3.jpg','레몬엠앤피','촬영 · 콘텐츠','촬영',243);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_205c9f2e089b65.jpg','삼성 바이오에피스','카탈로그','책자',244);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_08575f82af05d9.jpg','yummy BUSAN','로고','로고',245);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_7453a156716b4f.jpg','칠봉당','팜플렛','리플릿',246);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2ec38df181c4a2.jpg','하경코스메틱','촬영 · 콘텐츠','촬영',247);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e10ae23b29aa2c.jpg','중앙대학교','카탈로그','책자',248);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_df4e3f336a976b.jpg','inote','브랜딩','로고',249);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_59763a184413d7.jpg','미래에셋','3단 리플렛','리플릿',250);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_21fe4f28cfa745.jpg','넷세이프','촬영 · 콘텐츠','촬영',251);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_7a6821c90f5034.jpg','서울 종합방재센터','카탈로그','책자',252);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_46f3d2dc3864dc.jpg','하이트진로','리플렛','리플릿',253);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_70dcff1d795faf.jpg','공진','촬영 · 콘텐츠','촬영',254);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1cfc35b449cc45.jpg','우정사업본부','카탈로그','책자',255);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_0779840065fe59.jpg','대영에스에프','촬영 · 콘텐츠','촬영',256);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e0f0fa0266c957.jpg','이화여대','카탈로그','책자',257);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ce3c4e57bc1d8f.jpg','H2 COPERATION','촬영 · 콘텐츠','촬영',258);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_733341b7be12bb.jpg','대우','브로슈어','책자',259);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_0741cdb968547a.jpg','에필성형외과','촬영 · 콘텐츠','촬영',260);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5985e732d9c1f2.jpg','두산 선박','카탈로그','책자',261);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a737e9000b19bf.jpg','한경푸드시스템','촬영 · 콘텐츠','촬영',262);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b8dc0fcd26b4fe.jpg','단양군','브로슈어','책자',263);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_229c3a4c36fcec.jpg','탑솔라그룹','촬영 · 콘텐츠','촬영',264);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a3a0b6f0e16885.jpg','KB 국민은행','브로슈어','책자',265);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c44c6df5a5568f.jpg','조인엔지니어링','촬영 · 콘텐츠','촬영',266);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_076a99fd09e2b3.jpg','국립과학수사연구원','브로슈어','책자',267);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_135df1df869c8c.jpg','삼성정밀공업','촬영 · 콘텐츠','촬영',268);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4eacde642646d6.jpg','삼성 바이오에피스','브로슈어','책자',269);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_afa9bc5d8cd52d.jpg','헤븐리팜','촬영 · 콘텐츠','촬영',270);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b87807432eaa40.jpg','KB국민은행','브로슈어','책자',271);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e7b85158d6f52f.jpg','한국화학연구소','촬영 · 콘텐츠','촬영',272);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b81047e47ebbe6.jpg','삼성화재','브로슈어','책자',273);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_86b9177472a83a.jpg','용평리조트','촬영 · 콘텐츠','촬영',274);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9b5a4e595fdf11.jpg','트라텍','촬영 · 콘텐츠','촬영',275);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4af7de900a8580.jpg','참다한홍삼','촬영 · 콘텐츠','촬영',276);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5231f1a83a5432.jpg','진솔','촬영 · 콘텐츠','촬영',277);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e76956c6bcf089.jpg','오에스피','촬영 · 콘텐츠','촬영',278);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5df8a85525da5f.jpg','에스파이온','촬영 · 콘텐츠','촬영',279);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_928c3767c832a0.jpg','덕진섬유','촬영 · 콘텐츠','촬영',280);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2d12be44973a8e.jpg','셀로테크닉','촬영 · 콘텐츠','촬영',281);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_310b7a79642492.jpg','한국마사회시설관리협회','촬영 · 콘텐츠','촬영',282);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a1ef41d2742b23.jpg','대령숙수','촬영 · 콘텐츠','촬영',283);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_097019f3655ac0.jpg','그루기술','촬영 · 콘텐츠','촬영',284);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e6ff4e32e32e79.jpg','윈차이나','촬영 · 콘텐츠','촬영',285);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_187304d6625f4d.jpg','대현공업','촬영 · 콘텐츠','촬영',286);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1b47712cb02fb0.jpg','자이S&D','촬영 · 콘텐츠','촬영',287);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_13cc5061bc7636.jpg','크리미오','촬영 · 콘텐츠','촬영',288);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_67b3113382a1ef.jpg','네오파워텍','촬영 · 콘텐츠','촬영',289);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_735b1e9a326df7.jpg','미니멜츠','촬영 · 콘텐츠','촬영',290);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_cf64683bbb8a6b.jpg','족발상회','촬영 · 콘텐츠','촬영',291);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1ae2269856282b.jpg','다이닝브랜즈그룹(BHC그룹)','촬영 · 콘텐츠','촬영',292);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_44b5d489ac8ff7.jpg','씨앤씨글로벌','촬영 · 콘텐츠','촬영',293);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_12690e9675ae39.jpg','뷰티스','촬영 · 콘텐츠','촬영',294);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5d70bb94d2955f.jpg','이노맥스글로벌','촬영 · 콘텐츠','촬영',295);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_48d46b6294213a.jpg','유진정밀','촬영 · 콘텐츠','촬영',296);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a20404d639e704.jpg','언일전자','촬영 · 콘텐츠','촬영',297);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_6e87c9e66cd63f.jpg','CP컴퍼니','촬영 · 콘텐츠','촬영',298);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_676b8d8aa66d0b.jpg','레오폴드','촬영 · 콘텐츠','촬영',299);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4f22c6b464b07a.jpg','링크로스','촬영 · 콘텐츠','촬영',300);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a2dd8d380c0b7c.jpg','반디','촬영 · 콘텐츠','촬영',301);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_dbc69d4bf9fa97.jpg','루엠코리아','촬영 · 콘텐츠','촬영',302);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c7b6258ffd4ac9.png','인천창조경제혁신센터','촬영 · 콘텐츠','촬영',303);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3800594e8c03a3.jpg','한국중앙자원봉사센터','촬영 · 콘텐츠','촬영',304);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_17e7e2c85a956e.jpg','컬티랩스','촬영 · 콘텐츠','촬영',305);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a977d05c2214bc.jpg','퍼시픽인터켐','촬영 · 콘텐츠','촬영',306);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_f9d1b3bac0e539.jpg','HS 하이테크','촬영 · 콘텐츠','촬영',307);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_94cb4419f17199.png','서초문화재단','촬영 · 콘텐츠','촬영',308);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e01d8c62a400c2.jpg','하늘바이오 후라이드 깡! 오징어','촬영 · 콘텐츠','촬영',309);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_dc5da2abd4980b.jpg','레몬엠엔피 핸드크림 : 널','촬영 · 콘텐츠','촬영',310);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_18d2d5b982eb35.jpg','라미체피부과 Dr.LAMICHE','촬영 · 콘텐츠','촬영',311);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_27fced41d76c9a.jpg','카멜로테크 달이차','촬영 · 콘텐츠','촬영',312);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2db4e1da5cc18f.jpg','버튼앤라이프 BONBON 제모크림','촬영 · 콘텐츠','촬영',313);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_027b44367969b0.jpg','글로우앤드파워 Secret Glow Tea','촬영 · 콘텐츠','촬영',314);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_524d135bd6a3c9.jpg','제닉 ACTIVE REPAIR LINE','촬영 · 콘텐츠','촬영',315);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_6b03a69e661201.jpg','제닉 EXTRA COOLING ACTIVITY PATCH','촬영 · 콘텐츠','촬영',316);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e235c91be4c9ce.jpg','마켓팸','촬영 · 콘텐츠','촬영',317);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_84c1c7a9c27692.jpg','플래티넘 맥주','촬영 · 콘텐츠','촬영',318);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e761265dd12fa3.jpg','나노힐코스메틱','촬영 · 콘텐츠','촬영',319);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_24a0540ce20f9f.jpg','아이코닉스 잔망루피','촬영 · 콘텐츠','촬영',320);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5b9cf161e557cb.jpg','말캉슈즈 v2','촬영 · 콘텐츠','촬영',321);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ee28757130a483.jpg','말캉슈즈 v1','촬영 · 콘텐츠','촬영',322);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_470149f1988c80.jpg','클리아벨라 바이럴','촬영 · 콘텐츠','촬영',323);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9a24de25917f34.jpg','TUPA','촬영 · 콘텐츠','촬영',324);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_74ffbb842837c6.jpg','아크네엑시트 여드름 폼클랜징 바이럴','촬영 · 콘텐츠','촬영',325);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2f203306839934.jpg','세꾸비 캠핑 바베큐그릴','촬영 · 콘텐츠','촬영',326);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a96812133da0b1.jpg','클리아벨라 HOW','촬영 · 콘텐츠','촬영',327);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_bc6f34b4c2de96.jpg','아크네엑시트 여드름 폼클랜징 HOW','촬영 · 콘텐츠','촬영',328);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_05e55f929459f4.jpg','더미래나인 하이퍼오투 750ml','촬영 · 콘텐츠','촬영',329);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c29a9f841df316.png','더미래나인 하이퍼오투 1L','촬영 · 콘텐츠','촬영',330);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c759f664437a92.jpg','레츠퀸 에어볼륨브러쉬','촬영 · 콘텐츠','촬영',331);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_68bbbbd1311b9c.jpg','레츠퀸 드라이어기','촬영 · 콘텐츠','촬영',332);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c03013949045fe.png','레츠퀸 무선 LED 넥밴드 선풍기','촬영 · 콘텐츠','촬영',333);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8ceed5e86b3755.jpg','테스크 요소수 품질 실시간 센싱 시스템','촬영 · 콘텐츠','촬영',334);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4548cf0d807ef6.jpg','아크네엑시트 여드름 폼클랜징','촬영 · 콘텐츠','촬영',335);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_99b45fa39fd416.jpg','그린웹 파우제 글라스슬라이드','촬영 · 콘텐츠','촬영',336);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_bf911f35486c47.jpg','그린웹 파우제 플랙스 월','촬영 · 콘텐츠','촬영',337);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ea45627669cacf.jpg','KC 인더스트리얼','촬영 · 콘텐츠','촬영',338);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_37864f3bfbd9af.jpg','트레이더스 전복차우더','촬영 · 콘텐츠','촬영',339);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3f776309b7dd5f.jpg','신라명가 경주빵','촬영 · 콘텐츠','촬영',340);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e2046595db951a.jpg','IT FACTORY','촬영 · 콘텐츠','촬영',341);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_f0a91a17dadef6.jpg','MKIN Berberine Cleanser','촬영 · 콘텐츠','촬영',342);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2f89d290aa37d0.jpg','말콤 브랜디드','영상','촬영',343);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_183ef7b9e1ce00.jpg','프롬비랩','촬영 · 콘텐츠','촬영',344);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_77e228e66577b6.jpg','지원바이오 SOQU','촬영 · 콘텐츠','촬영',345);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_0a3b8f6fca1f7e.jpg','칸핏 브랜디드','촬영 · 콘텐츠','촬영',346);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_bae79e422d0918.jpg','칸핏 프로모션','촬영 · 콘텐츠','촬영',347);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a3c74824803039.jpg','대동고려삼','촬영 · 콘텐츠','촬영',348);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_edf4775a5a1754.jpg','번영푸드','촬영 · 콘텐츠','촬영',349);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2539b6b0eb65a6.jpg','화인바이오','촬영 · 콘텐츠','촬영',350);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_501bbf614410da.jpg','연세생활건강','촬영 · 콘텐츠','촬영',351);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b454377ed5df80.jpg','서울우유','촬영 · 콘텐츠','촬영',352);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_841aad8865b218.jpg','횡성농협','촬영 · 콘텐츠','촬영',353);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2d444e8a9d0b4a.jpg','거인식품','촬영 · 콘텐츠','촬영',354);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_10d8a8c6a1bc22.jpg','베리굿스트로베리','촬영 · 콘텐츠','촬영',355);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b4347ad8f4062b.jpg','서진바이오팜','촬영 · 콘텐츠','촬영',356);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_f62288a030ed7d.jpg','더에이치큐','촬영 · 콘텐츠','촬영',357);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9abd477864e1ef.jpg','오뚜기 컵밥','촬영 · 콘텐츠','촬영',358);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ebe1554e994ea9.jpg','농부마을','촬영 · 콘텐츠','촬영',359);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_7c87af0b1a5897.jpg','우유청년','촬영 · 콘텐츠','촬영',360);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_bd5eba8276f6d4.jpg','황금어장','촬영 · 콘텐츠','촬영',361);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4855492aade9dc.jpg','고삼농협 착한들','촬영 · 콘텐츠','촬영',362);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_19677c540cd422.jpg','더건강협동','촬영 · 콘텐츠','촬영',363);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_20398e05fe3e85.jpg','헤텍스 베네퍼피','촬영 · 콘텐츠','촬영',364);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_48296cccecda04.jpg','시아스','촬영 · 콘텐츠','촬영',365);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_cd00b2e08ee9c5.jpg','청담','촬영 · 콘텐츠','촬영',366);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_dc21fd0b7ceba7.jpg','자미','촬영 · 콘텐츠','촬영',367);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_52bf4769126895.jpg','오뚜기','촬영 · 콘텐츠','촬영',368);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4f7f8945481083.jpg','피에르파브르','촬영 · 콘텐츠','촬영',369);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_029d2d79bab010.jpg','알에이치앤비','촬영 · 콘텐츠','촬영',370);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_17e18a733bdb76.jpg','삼성웰스토리','촬영 · 콘텐츠','촬영',371);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c29054e43c772d.jpg','투쿨포스쿨','촬영 · 콘텐츠','촬영',372);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_d71319e6eb8d0d.jpg','소오름','촬영 · 콘텐츠','촬영',373);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_69c172e7fafe20.jpg','고삼농협','촬영 · 콘텐츠','촬영',374);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_528e4352278468.jpg','정남농협','촬영 · 콘텐츠','촬영',375);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_6e64eb08008493.jpg','생즙연구소','촬영 · 콘텐츠','촬영',376);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4bc67f36d76ea1.jpg','더큰수산','촬영 · 콘텐츠','촬영',377);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_2382faf39e85e0.jpg','농협','촬영 · 콘텐츠','촬영',378);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_7cb0eaad0902b2.jpg','만복가','촬영 · 콘텐츠','촬영',379);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9b3620c71abf05.jpg','벨치즈코리아','촬영 · 콘텐츠','촬영',380);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3761044cd346b9.jpg','서울프로폴리스','촬영 · 콘텐츠','촬영',381);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ee6ecf32a04520.jpg','소담장','촬영 · 콘텐츠','촬영',382);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4e7e9cda635d1d.jpg','이노뮤바이오텍','촬영 · 콘텐츠','촬영',383);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1ad6bd4e2aa74d.jpg','굽네 지엔몰','촬영 · 콘텐츠','촬영',384);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9ac8aa90354d87.jpg','청원인터내셔날','촬영 · 콘텐츠','촬영',385);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5306d9c7d44e60.jpg','하루네이처','촬영 · 콘텐츠','촬영',386);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_88556c62104ce7.jpg','편백치드','촬영 · 콘텐츠','촬영',387);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_4b98b7c9cf58b2.jpg','웅진','촬영 · 콘텐츠','촬영',388);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1b9a0e7b3e03a7.jpg','아이리스브라이트','촬영 · 콘텐츠','촬영',389);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_68a9e865df16b0.jpg','레이티드그린','촬영 · 콘텐츠','촬영',390);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_0710eabda082ee.jpg','누하드','촬영 · 콘텐츠','촬영',391);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_09578713dcc45b.jpg','그레이잇','촬영 · 콘텐츠','촬영',392);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_e9230f2582438f.jpg','LBB','촬영 · 콘텐츠','촬영',393);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_868b09e0c00d05.jpg','한독 테라큐민','촬영 · 콘텐츠','촬영',394);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8c4e23f32a8c83.jpg','한독 레디큐','촬영 · 콘텐츠','촬영',395);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_61bdfd2ef07d19.jpg','오뚜기 헝가리안 비프 굴라쉬','촬영 · 콘텐츠','촬영',396);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9322011ce2eae9.jpg','오뚜기 파운드케이크','촬영 · 콘텐츠','촬영',397);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1f4d060e972175.jpg','수미과','촬영 · 콘텐츠','촬영',398);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c48f12bdae6c51.jpg','서울우유 치즈선물세트','촬영 · 콘텐츠','촬영',399);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8635a742b64ae7.jpg','배상면주가 도소주','촬영 · 콘텐츠','촬영',400);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1472356cd8d963.jpg','배상면주가 느린마을 막걸리','촬영 · 콘텐츠','촬영',401);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1bd767fb2104c5.jpg','농협 알찬밤묵','촬영 · 콘텐츠','촬영',402);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_72f27250e6ce56.jpg','바츠코리아','촬영 · 콘텐츠','촬영',403);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_05786f290913a5.jpg','돔모드','촬영 · 콘텐츠','촬영',404);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c93e5233b3675e.jpg','서울우유 검은콩 호두아몬드 두유','촬영 · 콘텐츠','촬영',405);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_3702f068d6c883.jpg','납작막창','촬영 · 콘텐츠','촬영',406);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b573685f7abc9d.jpg','농협 건나물','촬영 · 콘텐츠','촬영',407);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_6f4eee1235e5b2.jpg','서울우유 슬라이스 치즈','촬영 · 콘텐츠','촬영',408);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b7b6bd786f0293.jpg','농협몰 홍삼 대보원','촬영 · 콘텐츠','촬영',409);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b7cbfefc268565.jpg','농협몰 우리땅 우리콩','촬영 · 콘텐츠','촬영',410);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_932a0d3066778f.jpg','로렌츄컴퍼니','촬영 · 콘텐츠','촬영',411);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_74bb47e74d20c2.jpg','바이트랩','촬영 · 콘텐츠','촬영',412);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_11b891d36db156.jpg','꼬소명가','촬영 · 콘텐츠','촬영',413);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5aac50d6ca134f.gif','이디야','촬영 · 콘텐츠','촬영',414);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_359ab8766f3f60.gif','정관장','촬영 · 콘텐츠','촬영',415);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ae8c46a819b93f.gif','달바','촬영 · 콘텐츠','촬영',416);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_583bd73e9aca42.gif','디어부','촬영 · 콘텐츠','촬영',417);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_7e111fe4c1848a.gif','Dr.martin','촬영 · 콘텐츠','촬영',418);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_f1803810bc64e7.gif','Fila','촬영 · 콘텐츠','촬영',419);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_b5806e6e927c8d.gif','Prada handbag','촬영 · 콘텐츠','촬영',420);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_40c5dc9b6bc890.gif','Prada heel','촬영 · 콘텐츠','촬영',421);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_d02dcab7881655.gif','스타벅스','촬영 · 콘텐츠','촬영',422);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9816062393dd35.gif','Sneakers','촬영 · 콘텐츠','촬영',423);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_8015b0ddb35bf8.gif','씨앤씨아이디어스','촬영 · 콘텐츠','촬영',424);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_ec74e50ce3cabb.jpg','25well','촬영 · 콘텐츠','촬영',425);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_745dcb7c95eda7.jpg','Depound Shooper','촬영 · 콘텐츠','촬영',426);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_615b0d65fb341f.jpg','Dr.Martin','촬영 · 콘텐츠','촬영',427);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_1e6c837c13c29b.jpg','Omega','촬영 · 콘텐츠','촬영',428);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_09121e84a2a878.jpg','Prada','촬영 · 콘텐츠','촬영',429);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_98e0c721279955.jpg','Tumi-bag','촬영 · 콘텐츠','촬영',430);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_06bab095b38314.jpg','sneakers','촬영 · 콘텐츠','촬영',431);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_08373bab16cd0c.jpg','ART SHOT','촬영 · 콘텐츠','촬영',432);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_abdfbae0c1235d.jpg','퓨어랜드','촬영 · 콘텐츠','촬영',433);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_dfc52864208d45.jpg','한독','촬영 · 콘텐츠','촬영',434);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_dba8f708e443a3.png','써치엠','촬영 · 콘텐츠','촬영',435);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_a37478deced5e3.jpg','코지플렉스','촬영 · 콘텐츠','촬영',436);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_9445b556ce7da0.png','핏인라이프','촬영 · 콘텐츠','촬영',437);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_5e50f46e091083.jpg','유니크코리아','촬영 · 콘텐츠','촬영',438);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_14b4d41dc16160.jpg','심코인터내셔널','촬영 · 콘텐츠','촬영',439);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c76e16eb7059e4.jpg','리온트','촬영 · 콘텐츠','촬영',440);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_cd2e90904b07f7.jpg','나성엘엔씨','촬영 · 콘텐츠','촬영',441);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_24d3a705a6f896.jpg','Black Loel','패키지 촬영','촬영',442);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_26c5aaa922072a.jpg','오뚜기','식품 촬영','촬영',443);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_95a5e4fe8b69c4.jpg','직연들기름','제품 촬영','촬영',444);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_73d9e7d6bb303d.jpg','호감','패키지 촬영','촬영',445);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_41df29c2adfba7.jpg','dining brands','웹사이트','촬영',446);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_c52d3d55227f2b.jpg','웹사이트 모음','촬영 · 콘텐츠','촬영',447);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_50ad0176982cff.jpg','cozywhite','상세페이지','촬영',448);
INSERT INTO `portfolio`(image,title,type,category,sort_order) VALUES('theme/assets/first/pf2/p_42ce6aa0487afd.jpg','NATURE','영상','촬영',449);

-- 히어로 3개
INSERT INTO `hero`(sort_order,title,eyebrow,subtitle,image,btn1_link,text_color) VALUES(0,'결과로 증명하는
*공공기관* 디자인 파트너','브로슈어 제작','국립과학수사연구원 — '진실을 밝히는 과학의 힘'<br>기관 브로슈어 기획·디자인·인쇄','theme/assets/first/banner_Gukgwasu01.jpg','portfolio.html','light');
INSERT INTO `hero`(sort_order,title,eyebrow,subtitle,image,btn1_link,text_color) VALUES(1,'금융권이 선택한
*정확한* 편집 디자인','사보 제작','KB국민은행 — 글로벌 네트워크 사보 내지<br>복잡한 정보를 명확한 편집으로','theme/assets/first/banner_kb01.jpg','portfolio.html','light');
INSERT INTO `hero`(sort_order,title,eyebrow,subtitle,image,btn1_link,text_color) VALUES(2,'캠페인의 얼굴을 만드는
*포스터* 디자인','포스터 제작','이화여자대학교 — AI 산학협력 세미나 포스터<br>행사·전시·프로모션 포스터 제작','theme/assets/first/banner_Ewha01.jpg','portfolio.html','light');

-- FAQ 저장분 0행

-- 칼럼 0개

INSERT INTO `settings`(k,v) VALUES('domain','https://incheondesign.co.kr');
INSERT INTO `settings`(k,v) VALUES('headCode','');